import swaggerAutogen from 'swagger-autogen'

const swagger = swaggerAutogen();

const outputFile = './swagger_output.json'
const endpointsFiles = ["./src/routes/*.js"]

const doc = {
    swagger: "2.0",
    info: {
        version: "1.0.0",
        title: "PermutaGov",
        description: "Documentation automatically generated by the <b>swagger-autogen</b> module."
    },
    host: "localhost:8080",
    basePath: "/",
    schemes: ["http", "https"],
    consumes: ['application/json'],
    produces: ['application/json'],
    paths: {},
    tags: [
        {
            "name": "User",
            "description": "Endpoints"
        }
    ],
    definitions: {
        // Parents: {
        //     father: "Simon Doe",
        //     mother: "Marie Doe"
        // },
        User: {
            _id: "6390fd9dasd1sad14adb4f9a023b",
            name: "Josá da Silva",
            cpf: 12345678912,
            email: "emailusuario@provedor.com",
            isAdmin: false,
            createdAt: "2022-12-07T20:54:53.302Z",
            updatedAt: "2022-12-07T20:54:53.302Z",
            _v: 0
            // parents: {
            //     $ref: '#/definitions/Parents'
            // },
        },
        LoggedUser: {
            user: {$ref: '#/definitions/User'},
            token: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MzkwZmQ5ZDE4MTRiYjRmOWEwMjgzM2MiLCJuYW1lIjoiSnVsaWFubyBIYXVzZW4gT2xpdmVpcmEgZGEgQ29zdGEiLCJlbWFpbCI6Imp1bGlhbm9oY29zdGFAZ21haWwuY29tIiwiaWF0IjoxNjcwNDQ2NzU3LCJleHAiOjE2NzA0ODk5NTd9.KAN7PHGJh2CHI1EtdquzMvUMwyiV_e2rOu9_W_WCKqc"
            // parents: {
            //     $ref: '#/definitions/Parents'
            // },
        },
        RegisterUser: {
            $name: "José da Silva",
            $cpf: 12345678912,
            $email: "emailusuario@provedor.com",
            $password: "SenhaValida75!"
        },
        SignIn: {
            $email: "emailusuario@provedor.com",
            $password: "SenhaValida75!"
        }
    }
}

swagger(outputFile, endpointsFiles, doc).then(_ => {
})

// swagger(outputFile, endpointsFiles, doc).then(() => {
//     require('./src/server')           // Your project's root file
// })